name: scibert
channels:
  - menpo
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - attrs=19.1.0
  - backcall=0.1.0
  - blas=1.0
  - bleach=3.1.0
  - certifi=2019.9.11
  - cffi=1.12.3
  - cpuonly=1.0
  - cuda90=1.0
  - cudatoolkit=10.0.130
  - decorator=4.4.0
  - defusedxml=0.5.0
  - entrypoints=0.3
  - freetype=2.9.1
#  - icc_rt=2019.0.0
  - intel-openmp=2019.4
  - ipykernel=5.1.2
  - ipython=7.8.0
  - ipython_genutils=0.2.0
  - jedi=0.15.1
  - jinja2=2.10.1
  - jpeg=9b
  - json5=0.8.5
  - jsonschema=3.0.2
  - jupyter_client=5.3.1
  - jupyter_core=4.4.0
  - jupyterlab=1.1.3
  - jupyterlab_server=1.0.6
  - libpng=1.6.37
  - libsodium=1.0.17
  - libtiff=4.0.10
#  - m2w64-gcc-libgfortran=5.3.0
#  - m2w64-gcc-libs=5.3.0
#  - m2w64-gcc-libs-core=5.3.0
#  - m2w64-gmp=6.1.0
#  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - markupsafe=1.1.1
  - mistune=0.8.4
  - mkl=2019.4
  - mkl-service=2.3.0
  - mkl_fft=1.0.14
  - mkl_random=1.0.2
#  - msys2-conda-epoch=20160418
  - nbconvert=5.6.0
  - nbformat=4.4.0
  - ninja=1.9.0
  - notebook=6.0.1
  - olefile=0.46
  - pandoc=2.7.3
  - pandocfilters=1.4.2
  - parso=0.5.1
  - pillow=6.2.0
  - pip=19.2.2
  - prometheus_client=0.7.1
  - prompt_toolkit=2.0.9
  - pycparser=2.19
  - pygments=2.4.2
  - pyrsistent=0.15.4
  - python=3.6.9
  - python-dateutil=2.8.0
  - pytorch=1.2.0
#  - pywinpty=0.5.5
  - send2trash=1.5.0
  - setuptools=41.0.1
  - six=1.12.0
  - sqlite=3.29.0
  - terminado=0.8.2
  - testpath=0.4.2
  - tk=8.6.8
  - torchvision=0.4.0
  - tornado=6.0.3
#  - vc=14.1
#  - vs2015_runtime=14.16.27012
  - webencodings=0.5.1
#  - wget=1.16.3
  - wheel=0.33.4
#  - wincertstore=0.2
#  - winpty=0.4.3
  - xz=5.2.4
  - zeromq=4.3.2
  - zlib=1.2.11
  - zstd=1.3.7
  - pip:
    - alabaster==0.7.12
    - allennlp==0.8.5
    - atomicwrites==1.3.0
    - babel==2.7.0
    - blis==0.2.4
    - boto3==1.9.228
    - botocore==1.12.228
    - chardet==3.0.4
    - click==7.0
    - colorama==0.4.1
    - conllu==1.3.1
    - cycler==0.10.0
    - cymem==2.0.2
    - docutils==0.15.2
    - editdistance==0.5.3
#    - en-core-web-sm==2.1.0
    - flaky==3.6.1
    - flask==1.1.1
    - flask-cors==3.0.8
    - ftfy==5.6
    - gevent==1.4.0
    - greenlet==0.4.15
    - h5py==2.10.0
    - idna==2.8
    - imagesize==1.1.0
    - importlib-metadata==0.22
    - ipython-genutils==0.2.0
    - itsdangerous==1.1.0
    - jmespath==0.9.4
    - joblib==0.14.0
    - jsonpickle==1.2
    - jupyter-client==5.3.2
    - jupyter-core==4.5.0
    - kiwisolver==1.1.0
    - libchebipy==1.0.9
    - matplotlib==3.1.1
    - more-itertools==7.2.0
    - murmurhash==1.0.2
    - nltk==3.4.5
    - numpy==1.16.5
    - numpydoc==0.9.1
    - overrides==1.9
    - packaging==19.1
    - pandas==0.25.1
    - parsimonious==0.8.1
    - pickleshare==0.7.5
    - plac==0.9.6
    - pluggy==0.13.0
    - preshed==2.0.1
    - protobuf==3.9.1
    - py==1.8.0
    - pyparsing==2.4.2
    - pytest==5.1.2
    - pytorch-pretrained-bert==0.6.2
    - pytorch-transformers==1.1.0
    - pytz==2019.2
#    - pywin32==225
    - pyzmq==18.1.0
    - regex==2019.08.19
    - requests==2.22.0
    - responses==0.10.6
    - s3transfer==0.2.1
    - sacremoses==0.0.34
    - scikit-learn==0.21.3
    - scipy==1.3.1
    - sentencepiece==0.1.83
    - sklearn==0.0
    - snowballstemmer==1.9.1
    - spacy==2.1.8
    - sphinx==2.2.0
    - sphinxcontrib-applehelp==1.0.1
    - sphinxcontrib-devhelp==1.0.1
    - sphinxcontrib-htmlhelp==1.0.2
    - sphinxcontrib-jsmath==1.0.1
    - sphinxcontrib-qthelp==1.0.2
    - sphinxcontrib-serializinghtml==1.1.3
    - sqlparse==0.3.0
    - srsly==0.1.0
    - tensorboardx==1.8
    - thinc==7.0.8
    - tqdm==4.35.0
    - traitlets==4.3.2
    - transformers==2.0.0
    - unidecode==1.1.1
    - urllib3==1.25.3
    - wasabi==0.2.2
    - wcwidth==0.1.7
    - werkzeug==0.15.6
    - word2number==1.1
    - zipp==0.6.0


